version: "3.9"

services:
  b2b:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./b2b:/b2b
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py wait_for_smtp &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - smtp4dev
      - redis
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "3001:80"
      - "2525:25"
    volumes:
      - smtp4dev-data:/smtp4dev

  db:
    image: postgres:13-alpine
    ports:
      - 6432:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  redis:
    image: redis:7.0.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - dev-redis-data:/bitnami/redis/data

  celery:
    build:
      context: .
      args:
        - DEV=true
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py wait_for_smtp &&
             celery -A b2b worker --loglevel=info"
    depends_on:
      - db
      - smtp4dev
      - redis
    volumes:
      - ./b2b:/b2b
    env_file:
      - ./.env

  celery-beat:
    build:
      context: .
      args:
        - DEV=true
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py wait_for_smtp &&
             celery -A b2b beat --loglevel=info"
    depends_on:
      - db
      - smtp4dev
      - redis
    volumes:
      - ./b2b:/b2b
    env_file:
      - ./.env

volumes:
  dev-db-data:
  dev-static-data:
  smtp4dev-data:
  dev-redis-data:
