version: "3.9"

services:
  b2b:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./b2b:/b2b
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - CLIENT_URL=${CLIENT_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=${DEBUG}
      - DEFAULT_FROM_EMAIL=from@snnbotchway.com
      - EMAIL_HOST=smtp4dev
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_PORT=25
      - SECRET_KEY=${SECRET_KEY}
      - SOCIAL_AUTH_ALLOWED_REDIRECT_URIS=${SOCIAL_AUTH_ALLOWED_REDIRECT_URIS}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=${SOCIAL_AUTH_GOOGLE_OAUTH2_KEY}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=${SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET}
    depends_on:
      - db
      - smtp4dev

  db:
    image: postgres:13-alpine
    ports:
      - 6432:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "3001:80"
      - "2525:25"
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  dev-db-data:
  dev-static-data:
  smtp4dev-data:
